### PR TITLE
chore: release v0.6.1

### PR DESCRIPTION
**Pull request by obycode**

### CODE REVIEW

**Comment by obycode** [comment]
I will push another branch and open a PR to develop to fix the npm audit error. Do not merge this yet.

**Comment by obycode** [comment]
Let's merge this after #68.

**Comment by obycode** [comment]
Ok, I believe this is good to go now if you approve @lgalabru.

**Review by lgalabru — APPROVED** [review]
Let's merge once the CI gives us a green light!

**Pull request merged**
